//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buildings
    {
        public Buildings()
        {
            this.UserBuildings = new HashSet<UserBuildings>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public int Percent_price_per_lvl { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int Product_per_h { get; set; }
        public int Destr_price { get; set; }
        public int Percent_product_per_lvl { get; set; }
        public int Products_ID { get; set; }
    
        public virtual ICollection<UserBuildings> UserBuildings { get; set; }
        public virtual Products Products { get; set; }
    }
}
