//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.UserProducts = new HashSet<UserProducts>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Price_per_unit { get; set; }
        public string Unit { get; set; }
    
        public virtual ICollection<UserProducts> UserProducts { get; set; }
        public virtual Buildings Buildings { get; set; }
    }
}
