//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBuildings
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public int X_pos { get; set; }
        public int Y_pos { get; set; }
        public int Lvl { get; set; }
        public int Building_ID { get; set; }
    
        public virtual Buildings Buildings { get; set; }
        public virtual AspNetUsers User { get; set; }
    }
}
