//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProducts
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public string ProductName { get; set; }
        public int Value { get; set; }
        public int Product_ID { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual AspNetUsers User { get; set; }
    }
}
